import { NextResponse } from "next/server";

// Base de datos de ciudades principales por país
const citiesDatabase = {
  ES: { name: "España", cities: ["Madrid", "Barcelona", "Valencia", "Sevilla", "Zaragoza", "Málaga", "Murcia", "Palma", "Bilbao", "Alicante", "Córdoba", "Valladolid", "Vigo", "Gijón", "Granada", "A Coruña", "Vitoria", "Elche", "Oviedo", "Santa Cruz de Tenerife", "Pamplona", "Santander", "San Sebastián", "Burgos", "Salamanca", "Albacete", "Logroño", "Badajoz", "Huelva", "Lleida", "Tarragona", "León", "Cádiz", "Jaén", "Ourense", "Lugo", "Girona", "Cáceres", "Toledo", "Guadalajara", "Castellón", "Almería", "Pontevedra", "Cuenca", "Ávila", "Segovia", "Soria", "Teruel", "Huesca", "Zamora", "Palencia"] },
  MX: { name: "México", cities: ["Ciudad de México", "Guadalajara", "Monterrey", "Puebla", "Tijuana", "León", "Juárez", "Zapopan", "Mérida", "San Luis Potosí", "Aguascalientes", "Hermosillo", "Saltillo", "Mexicali", "Culiacán", "Querétaro", "Morelia", "Chihuahua", "Cancún", "Acapulco", "Veracruz", "Toluca", "Villahermosa", "Tuxtla Gutiérrez", "Oaxaca", "Durango", "Mazatlán", "Tampico", "Cuernavaca", "Pachuca", "Campeche", "La Paz", "Colima", "Zacatecas", "Tlaxcala", "Chetumal", "Guanajuato", "Playa del Carmen", "Puerto Vallarta", "Los Cabos"] },
  AR: { name: "Argentina", cities: ["Buenos Aires", "Córdoba", "Rosario", "Mendoza", "La Plata", "San Miguel de Tucumán", "Mar del Plata", "Salta", "Santa Fe", "San Juan", "Resistencia", "Neuquén", "Santiago del Estero", "Corrientes", "Bahía Blanca", "San Salvador de Jujuy", "Posadas", "Paraná", "Formosa", "San Luis", "Catamarca", "La Rioja", "Río Gallegos", "Ushuaia", "Rawson", "Viedma", "Santa Rosa", "San Fernando del Valle", "Comodoro Rivadavia", "Bariloche", "Puerto Madryn", "Villa Carlos Paz", "Tandil", "Olavarría", "Junín", "Pergamino", "Rafaela", "Venado Tuerto", "Villa María", "Río Cuarto"] },
  CO: { name: "Colombia", cities: ["Bogotá", "Medellín", "Cali", "Barranquilla", "Cartagena", "Cúcuta", "Bucaramanga", "Pereira", "Santa Marta", "Ibagué", "Pasto", "Manizales", "Neiva", "Soledad", "Villavicencio", "Armenia", "Soacha", "Valledupar", "Montería", "Itagüí", "Palmira", "Buenaventura", "Floridablanca", "Sincelejo", "Popayán", "Barrancabermeja", "Tunja", "Girardot", "Riohacha", "Apartadó", "Quibdó", "Sogamoso", "Florencia", "Yopal", "Leticia", "Mocoa", "Mitú", "Puerto Carreño", "Inírida", "San José del Guaviare"] },
  CL: { name: "Chile", cities: ["Santiago", "Valparaíso", "Concepción", "La Serena", "Antofagasta", "Temuco", "Rancagua", "Talca", "Arica", "Chillán", "Puerto Montt", "Iquique", "Coquimbo", "Osorno", "Valdivia", "Calama", "Punta Arenas", "Copiapó", "Los Ángeles", "Curicó", "Quilpué", "Villa Alemana", "San Bernardo", "Puente Alto", "Maipú", "La Florida", "Las Condes", "Viña del Mar", "Talcahuano", "San Pedro de la Paz", "Coronel", "Lota", "Penco", "Tomé", "Angol", "Victoria", "Villarrica", "Pucón", "Castro", "Ancud"] },
  PE: { name: "Perú", cities: ["Lima", "Arequipa", "Trujillo", "Chiclayo", "Piura", "Iquitos", "Cusco", "Chimbote", "Huancayo", "Tacna", "Juliaca", "Ica", "Pucallpa", "Cajamarca", "Sullana", "Ayacucho", "Chincha Alta", "Huánuco", "Tarapoto", "Puno", "Tumbes", "Talara", "Paita", "Jaén", "Huaraz", "Moyobamba", "Cerro de Pasco", "Abancay", "Puerto Maldonado", "Moquegua", "Chachapoyas", "Huancavelica", "Nazca", "Mollendo", "Camaná", "Yungay", "Tarma", "La Oroya", "Satipo", "Tingo María"] },
  US: { name: "Estados Unidos", cities: ["New York", "Los Angeles", "Chicago", "Houston", "Phoenix", "Philadelphia", "San Antonio", "San Diego", "Dallas", "San Jose", "Austin", "Jacksonville", "Fort Worth", "Columbus", "Indianapolis", "Charlotte", "San Francisco", "Seattle", "Denver", "Washington", "Boston", "El Paso", "Nashville", "Detroit", "Portland", "Las Vegas", "Memphis", "Louisville", "Baltimore", "Milwaukee", "Albuquerque", "Tucson", "Fresno", "Sacramento", "Kansas City", "Atlanta", "Miami", "Oakland", "Minneapolis", "Cleveland", "New Orleans", "Tampa", "Honolulu", "Anchorage", "Orlando", "Pittsburgh", "Cincinnati", "St. Louis", "Salt Lake City", "Buffalo"] },
  GB: { name: "Reino Unido", cities: ["London", "Birmingham", "Manchester", "Glasgow", "Liverpool", "Bristol", "Sheffield", "Leeds", "Edinburgh", "Leicester", "Coventry", "Bradford", "Cardiff", "Belfast", "Nottingham", "Kingston upon Hull", "Newcastle upon Tyne", "Stoke-on-Trent", "Southampton", "Derby", "Portsmouth", "Brighton", "Plymouth", "Wolverhampton", "Reading", "Aberdeen", "Dundee", "Swansea", "Milton Keynes", "Northampton", "Norwich", "Luton", "Swindon", "Warrington", "Bournemouth", "Peterborough", "Stockport", "Oxford", "Cambridge", "York"] },
  FR: { name: "Francia", cities: ["Paris", "Marseille", "Lyon", "Toulouse", "Nice", "Nantes", "Strasbourg", "Montpellier", "Bordeaux", "Lille", "Rennes", "Reims", "Le Havre", "Saint-Étienne", "Toulon", "Grenoble", "Dijon", "Angers", "Nîmes", "Villeurbanne", "Saint-Denis", "Le Mans", "Aix-en-Provence", "Clermont-Ferrand", "Brest", "Tours", "Limoges", "Amiens", "Perpignan", "Metz", "Besançon", "Orléans", "Rouen", "Mulhouse", "Caen", "Nancy", "Saint-Denis", "Argenteuil", "Roubaix", "Tourcoing"] },
  DE: { name: "Alemania", cities: ["Berlin", "Hamburg", "Munich", "Cologne", "Frankfurt", "Stuttgart", "Düsseldorf", "Leipzig", "Dortmund", "Essen", "Bremen", "Dresden", "Hanover", "Nuremberg", "Duisburg", "Bochum", "Wuppertal", "Bielefeld", "Bonn", "Münster", "Mannheim", "Karlsruhe", "Augsburg", "Wiesbaden", "Mönchengladbach", "Gelsenkirchen", "Aachen", "Braunschweig", "Kiel", "Chemnitz", "Halle", "Magdeburg", "Freiburg", "Krefeld", "Mainz", "Lübeck", "Erfurt", "Oberhausen", "Rostock", "Kassel"] },
  IT: { name: "Italia", cities: ["Rome", "Milan", "Naples", "Turin", "Palermo", "Genoa", "Bologna", "Florence", "Bari", "Catania", "Venice", "Verona", "Messina", "Padua", "Trieste", "Taranto", "Brescia", "Parma", "Prato", "Modena", "Reggio Calabria", "Reggio Emilia", "Perugia", "Ravenna", "Livorno", "Cagliari", "Foggia", "Rimini", "Salerno", "Ferrara", "Sassari", "Latina", "Giugliano", "Monza", "Siracusa", "Pescara", "Bergamo", "Forlì", "Trento", "Vicenza"] },
  BR: { name: "Brasil", cities: ["São Paulo", "Rio de Janeiro", "Brasília", "Salvador", "Fortaleza", "Belo Horizonte", "Manaus", "Curitiba", "Recife", "Porto Alegre", "Belém", "Goiânia", "Guarulhos", "Campinas", "São Luís", "São Gonçalo", "Maceió", "Duque de Caxias", "Natal", "Teresina", "Campo Grande", "Nova Iguaçu", "São Bernardo do Campo", "João Pessoa", "Santo André", "Osasco", "Jaboatão dos Guararapes", "Ribeirão Preto", "Uberlândia", "Sorocaba", "Contagem", "Aracaju", "Feira de Santana", "Cuiabá", "Joinville", "Aparecida de Goiânia", "Londrina", "Juiz de Fora", "Ananindeua", "Niterói"] },
  PT: { name: "Portugal", cities: ["Lisboa", "Porto", "Vila Nova de Gaia", "Amadora", "Braga", "Funchal", "Coimbra", "Setúbal", "Almada", "Agualva-Cacém", "Queluz", "Aveiro", "Évora", "Faro", "Guimarães", "Leiria", "Viseu", "Viana do Castelo", "Póvoa de Varzim", "Vila Real", "Santarém", "Bragança", "Castelo Branco", "Portalegre", "Guarda", "Ponta Delgada", "Angra do Heroísmo", "Horta", "Praia da Vitória", "Ribeira Grande", "Lagos", "Portimão", "Albufeira", "Tavira", "Olhão", "Silves", "Lagoa", "Loulé", "Figueira da Foz", "Caldas da Rainha"] },
  JP: { name: "Japón", cities: ["Tokyo", "Yokohama", "Osaka", "Nagoya", "Sapporo", "Kobe", "Kyoto", "Fukuoka", "Kawasaki", "Saitama", "Hiroshima", "Sendai", "Kitakyushu", "Chiba", "Sakai", "Niigata", "Hamamatsu", "Shizuoka", "Sagamihara", "Okayama", "Kumamoto", "Kagoshima", "Funabashi", "Hachioji", "Kawaguchi", "Himeji", "Matsuyama", "Higashiosaka", "Utsunomiya", "Matsudo", "Nishinomiya", "Ichikawa", "Kurashiki", "Oita", "Kanazawa", "Fukuyama", "Amagasaki", "Nagasaki", "Toyama", "Gifu"] },
  CN: { name: "China", cities: ["Shanghai", "Beijing", "Guangzhou", "Shenzhen", "Chengdu", "Tianjin", "Wuhan", "Dongguan", "Chongqing", "Nanjing", "Shenyang", "Hangzhou", "Xi'an", "Harbin", "Suzhou", "Qingdao", "Dalian", "Zhengzhou", "Shantou", "Jinan", "Changchun", "Kunming", "Changsha", "Taiyuan", "Xiamen", "Hefei", "Shijiazhuang", "Ürümqi", "Fuzhou", "Wuxi", "Zhongshan", "Wenzhou", "Nanning", "Nanchang", "Ningbo", "Guiyang", "Lanzhou", "Zibo", "Huizhou", "Yantai"] },
  IN: { name: "India", cities: ["Mumbai", "Delhi", "Bangalore", "Hyderabad", "Chennai", "Kolkata", "Ahmedabad", "Pune", "Surat", "Jaipur", "Lucknow", "Kanpur", "Nagpur", "Patna", "Indore", "Thane", "Bhopal", "Visakhapatnam", "Vadodara", "Firozabad", "Ludhiana", "Rajkot", "Agra", "Siliguri", "Nashik", "Faridabad", "Patiala", "Meerut", "Kalyan", "Vasai-Virar", "Varanasi", "Srinagar", "Dhanbad", "Jodhpur", "Amritsar", "Raipur", "Allahabad", "Coimbatore", "Jabalpur", "Gwalior"] },
  AU: { name: "Australia", cities: ["Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide", "Gold Coast", "Newcastle", "Canberra", "Sunshine Coast", "Wollongong", "Hobart", "Geelong", "Townsville", "Cairns", "Darwin", "Toowoomba", "Ballarat", "Bendigo", "Launceston", "Mackay", "Rockhampton", "Bunbury", "Bundaberg", "Hervey Bay", "Wagga Wagga", "Coffs Harbour", "Gladstone", "Mildura", "Shepparton", "Albury", "Port Macquarie", "Tamworth", "Orange", "Dubbo", "Geraldton", "Nowra", "Bathurst", "Warrnambool", "Albany", "Kalgoorlie"] },
  CA: { name: "Canadá", cities: ["Toronto", "Montreal", "Vancouver", "Calgary", "Edmonton", "Ottawa", "Winnipeg", "Quebec City", "Hamilton", "Kitchener", "London", "Victoria", "Halifax", "Oshawa", "Windsor", "Saskatoon", "Regina", "St. Catharines", "St. John's", "Barrie", "Kelowna", "Abbotsford", "Sudbury", "Kingston", "Saguenay", "Trois-Rivières", "Guelph", "Moncton", "Brantford", "Thunder Bay", "Saint John", "Peterborough", "Nanaimo", "Lethbridge", "Kamloops", "Red Deer", "Prince George", "Medicine Hat", "Drummondville", "Granby"] },
  KR: { name: "Corea del Sur", cities: ["Seoul", "Busan", "Incheon", "Daegu", "Daejeon", "Gwangju", "Suwon", "Ulsan", "Changwon", "Seongnam", "Goyang", "Yongin", "Bucheon", "Cheongju", "Ansan", "Jeonju", "Anyang", "Cheonan", "Namyangju", "Hwaseong", "Uijeongbu", "Jeju", "Gimhae", "Pohang", "Pyeongtaek", "Siheung", "Paju", "Gumi", "Iksan", "Gwangmyeong", "Gimpo", "Wonju", "Yangsan", "Gunsan", "Asan", "Sejong", "Gyeongsan", "Uiwang", "Hanam", "Chuncheon"] },
  RU: { name: "Rusia", cities: ["Moscow", "Saint Petersburg", "Novosibirsk", "Yekaterinburg", "Kazan", "Nizhny Novgorod", "Chelyabinsk", "Samara", "Omsk", "Rostov-on-Don", "Ufa", "Krasnoyarsk", "Voronezh", "Perm", "Volgograd", "Krasnodar", "Saratov", "Tyumen", "Tolyatti", "Izhevsk", "Barnaul", "Ulyanovsk", "Irkutsk", "Khabarovsk", "Yaroslavl", "Vladivostok", "Makhachkala", "Tomsk", "Orenburg", "Kemerovo", "Novokuznetsk", "Ryazan", "Astrakhan", "Naberezhnye Chelny", "Penza", "Lipetsk", "Kirov", "Cheboksary", "Tula", "Kaliningrad"] },
  ZA: { name: "Sudáfrica", cities: ["Johannesburg", "Cape Town", "Durban", "Pretoria", "Port Elizabeth", "Bloemfontein", "East London", "Nelspruit", "Kimberley", "Polokwane", "Rustenburg", "Pietermaritzburg", "Benoni", "Tembisa", "Vereeniging", "Boksburg", "Welkom", "Newcastle", "Krugersdorp", "Uitenhage", "Chatsworth", "Witbank", "Roodepoort", "Midrand", "Centurion", "Soweto", "Randburg", "Sandton", "Vanderbijlpark", "George", "Stellenbosch", "Paarl", "Worcester", "Mossel Bay", "Knysna", "Hermanus", "Franschhoek", "Simon's Town", "Oudtshoorn", "Graaff-Reinet"] },
  EG: { name: "Egipto", cities: ["Cairo", "Alexandria", "Giza", "Shubra El Kheima", "Port Said", "Suez", "Luxor", "Mansoura", "El Mahalla El Kubra", "Tanta", "Asyut", "Ismailia", "Faiyum", "Zagazig", "Aswan", "Damietta", "Damanhur", "Minya", "Beni Suef", "Qena", "Sohag", "Hurghada", "Sharm El Sheikh", "Marsa Matruh", "Dahab", "Siwa", "El Alamein", "Nuweiba", "Taba", "Safaga", "El Gouna", "Makadi Bay", "Soma Bay", "Marsa Alam", "El Quseir", "Berenice", "Ras Gharib", "El Tor", "Saint Catherine", "Abu Simbel"] },
  NZ: { name: "Nueva Zelanda", cities: ["Auckland", "Wellington", "Christchurch", "Hamilton", "Tauranga", "Napier-Hastings", "Dunedin", "Palmerston North", "Nelson", "Rotorua", "New Plymouth", "Whangarei", "Invercargill", "Whanganui", "Gisborne", "Blenheim", "Pukekohe", "Timaru", "Taupo", "Masterton", "Levin", "Ashburton", "Cambridge", "Queenstown", "Oamaru", "Whakatane", "Tokoroa", "Te Awamutu", "Waiheke Island", "Whitianga", "Thames", "Paihia", "Kerikeri", "Kaikoura", "Greymouth", "Hokitika", "Franz Josef", "Wanaka", "Arrowtown", "Te Anau"] },
  SV: { name: "El Salvador", cities: ["San Salvador", "Santa Ana", "San Miguel", "Mejicanos", "Santa Tecla", "Soyapango", "Apopa", "Delgado", "Ilopango", "Tonacatepeque", "San Martín", "Cuscatancingo", "San Marcos", "Antiguo Cuscatlán", "Ayutuxtepeque", "Nejapa", "Quezaltepeque", "Aguilares", "Chalchuapa", "Ahuachapán", "Sonsonate", "Usulután", "Zacatecoluca", "Cojutepeque", "San Vicente", "Sensuntepeque", "La Unión", "Metapán", "Izalco", "Nahuizalco", "Juayúa", "Ataco", "Apaneca", "La Libertad", "El Tunco", "El Zonte", "El Cuco", "Perquín", "Suchitoto", "Panchimalco"] },
  GT: { name: "Guatemala", cities: ["Guatemala City", "Mixco", "Villa Nueva", "Petapa", "San Juan Sacatepéquez", "Quetzaltenango", "Escuintla", "Chinautla", "Chimaltenango", "Huehuetenango", "Amatitlán", "Cobán", "Santa Catarina Pinula", "San Miguel Petapa", "Totonicapán", "Jalapa", "Puerto Barrios", "Antigua Guatemala", "Mazatenango", "Coatepeque", "Zacapa", "Chiquimula", "Jutiapa", "Retalhuleu", "Santa Lucía Cotzumalguapa", "Sololá", "Panajachel", "San Pedro La Laguna", "Santiago Atitlán", "Chichicastenango", "Flores", "Tikal", "Livingston", "Río Dulce", "Semuc Champey", "Lanquín", "Nebaj", "San Marcos", "Tecún Umán", "El Remate"] },
  HN: { name: "Honduras", cities: ["Tegucigalpa", "San Pedro Sula", "Choloma", "La Ceiba", "El Progreso", "Choluteca", "Comayagua", "Puerto Cortés", "La Lima", "Danlí", "Siguatepeque", "Juticalpa", "Villanueva", "Tocoa", "Tela", "Santa Rosa de Copán", "Olanchito", "Catacamas", "San Lorenzo", "Cofradía", "Copán Ruinas", "Roatán", "Utila", "Guanaja", "Trujillo", "Omoa", "Gracias", "La Esperanza", "Santa Bárbara", "Yoro", "Nacaome", "Langue", "Amapala", "San Marcos de Colón", "Nueva Ocotepeque", "La Paz", "Marcala", "Intibucá", "Sabá", "Sonaguera"] },
  NI: { name: "Nicaragua", cities: ["Managua", "León", "Masaya", "Matagalpa", "Chinandega", "Granada", "Estelí", "Tipitapa", "Ciudad Sandino", "Jinotega", "El Viejo", "Nueva Guinea", "Juigalpa", "Jalapa", "Bluefields", "Diriamba", "Ocotal", "Rivas", "Jinotepe", "Chichigalpa", "San Marcos", "Somoto", "Boaco", "Carazo", "Corinto", "Puerto Cabezas", "San Carlos", "San Juan del Sur", "Ometepe", "Isla de Maíz", "Masatepe", "Catarina", "San Juan de Oriente", "Niquinohomo", "La Paz Centro", "Nagarote", "El Sauce", "Sébaco", "Darío", "San Rafael del Sur"] },
  CR: { name: "Costa Rica", cities: ["San José", "Limón", "San Francisco", "Alajuela", "Liberia", "Paraíso", "Desamparados", "Puntarenas", "San Isidro", "Curridabat", "San Vicente", "Cartago", "Heredia", "Turrialba", "San Rafael", "Nicoya", "Guápiles", "Santa Cruz", "Ciudad Quesada", "Escazú", "Puerto Viejo", "La Fortuna", "Monteverde", "Manuel Antonio", "Jacó", "Tamarindo", "Nosara", "Sámara", "Montezuma", "Santa Teresa", "Cahuita", "Tortuguero", "Dominical", "Uvita", "Quepos", "Volcán Arenal", "Sarapiquí", "Orosi", "Zarcero", "Grecia"] },
  PA: { name: "Panamá", cities: ["Panama City", "San Miguelito", "Tocumen", "David", "Las Cumbres", "La Chorrera", "Pacora", "Colón", "Santiago", "Chitré", "Changuinola", "Penonomé", "Aguadulce", "La Concepción", "Arraiján", "Vista Alegre", "Chepo", "Antón", "Puerto Armuelles", "Bocas del Toro", "Boquete", "Portobelo", "El Valle de Antón", "Santa Catalina", "Pedasí", "Las Tablas", "Gamboa", "Isla Contadora", "San Blas", "Volcán", "Cerro Punta", "Santa Fe", "El Cope", "Soná", "Río Hato", "Coronado", "Gorgona", "San Carlos", "Chame", "Capira"] },
  EC: { name: "Ecuador", cities: ["Guayaquil", "Quito", "Cuenca", "Santo Domingo", "Machala", "Durán", "Manta", "Portoviejo", "Loja", "Ambato", "Esmeraldas", "Quevedo", "Riobamba", "Milagro", "Ibarra", "La Libertad", "Babahoyo", "Sangolquí", "Daule", "Latacunga", "Tulcán", "Chone", "Pasaje", "Santa Rosa", "Nueva Loja", "Huaquillas", "El Carmen", "Vinces", "Playas", "Salinas", "Montañita", "Puerto López", "Baños", "Otavalo", "Cotacachi", "Mindo", "Tena", "Puyo", "Macas", "Galápagos"] },
  VE: { name: "Venezuela", cities: ["Caracas", "Maracaibo", "Valencia", "Barquisimeto", "Maracay", "Ciudad Guayana", "Barcelona", "Maturín", "Petare", "Turmero", "Ciudad Bolívar", "Cumaná", "Mérida", "Barinas", "Cabimas", "Los Teques", "Puerto La Cruz", "Coro", "Guarenas", "San Cristóbal", "Ciudad Ojeda", "Guatire", "Punto Fijo", "Acarigua", "Carúpano", "El Tigre", "Guanare", "Valera", "San Fernando de Apure", "Porlamar", "Isla Margarita", "Los Roques", "Canaima", "Colonia Tovar", "Choroní", "Puerto Colombia", "Tucacas", "Morrocoy", "Mochima", "Gran Sabana"] },
  UY: { name: "Uruguay", cities: ["Montevideo", "Salto", "Ciudad de la Costa", "Paysandú", "Las Piedras", "Rivera", "Maldonado", "Tacuarembó", "Melo", "Mercedes", "Artigas", "Minas", "San José de Mayo", "Durazno", "Florida", "Treinta y Tres", "Rocha", "Fray Bentos", "Trinidad", "Carmelo", "Colonia del Sacramento", "Punta del Este", "La Paloma", "Piriápolis", "Atlántida", "Canelones", "Pando", "La Paz", "Progreso", "Santa Lucía", "Sarandí Grande", "Young", "Bella Unión", "Chuy", "José Ignacio", "Cabo Polonio", "La Pedrera", "Valizas", "Aguas Dulces", "Paso de los Toros"] },
  PY: { name: "Paraguay", cities: ["Asunción", "Ciudad del Este", "San Lorenzo", "Luque", "Capiatá", "Lambaré", "Fernando de la Mora", "Limpio", "Ñemby", "Encarnación", "Mariano Roque Alonso", "Pedro Juan Caballero", "Caaguazú", "Coronel Oviedo", "Itauguá", "Presidente Franco", "Paraguarí", "Villarrica", "Caacupé", "Concepción", "Pilar", "San Juan Bautista", "Areguá", "Ypacaraí", "San Bernardino", "Itá", "Yaguarón", "Villeta", "San Antonio", "Tobatí", "Altos", "Atyrá", "Arroyos y Esteros", "Emboscada", "Valenzuela", "Sapucai", "Quiindy", "Ybycuí", "Acahay", "Carapeguá"] },
  BO: { name: "Bolivia", cities: ["Santa Cruz de la Sierra", "El Alto", "La Paz", "Cochabamba", "Oruro", "Sucre", "Tarija", "Potosí", "Sacaba", "Quillacollo", "Montero", "Trinidad", "Warnes", "Yacuiba", "Riberalta", "La Guardia", "Viacha", "Tiquipaya", "Bermejo", "Cobija", "Villazón", "Camiri", "Tupiza", "Uyuni", "Copacabana", "Coroico", "Rurrenabaque", "Samaipata", "Concepción", "San Ignacio de Velasco", "San José de Chiquitos", "Puerto Suárez", "San Borja", "Reyes", "San Ramón", "Guayaramerín", "San Matías", "Roboré", "Ascensión de Guarayos", "Buena Vista"] },
  CU: { name: "Cuba", cities: ["Havana", "Santiago de Cuba", "Camagüey", "Holguín", "Santa Clara", "Guantánamo", "Bayamo", "Las Tunas", "Cienfuegos", "Pinar del Río", "Matanzas", "Ciego de Ávila", "Sancti Spíritus", "Manzanillo", "Cárdenas", "Palma Soriano", "Moa", "Morón", "Florida", "Contramaestre", "Nuevitas", "Trinidad", "Güines", "Artemisa", "San José de las Lajas", "Colón", "Sagua la Grande", "Nueva Gerona", "Jovellanos", "Varadero", "Viñales", "Baracoa", "Gibara", "Remedios", "Caibariém", "Playa Girón", "Cayo Coco", "Cayo Largo", "Cayo Santa María", "Guardalavaca"] },
  DO: { name: "República Dominicana", cities: ["Santo Domingo", "Santiago de los Caballeros", "Santo Domingo Este", "Santo Domingo Norte", "Santo Domingo Oeste", "San Pedro de Macorís", "La Romana", "San Cristóbal", "Puerto Plata", "San Francisco de Macorís", "Higüey", "La Vega", "Bonao", "Moca", "Baní", "Azua", "Mao", "San Juan de la Maguana", "Cotuí", "Barahona", "Nagua", "Punta Cana", "Bávaro", "Samaná", "Las Terrenas", "Sosúa", "Cabarete", "Jarabacoa", "Constanza", "Boca Chica", "Juan Dolio", "Bayahíbe", "Cabrera", "Río San Juan", "Montecristi", "Pedernales", "Jimaní", "Elías Piña", "Dajabón", "Santiago Rodríguez"] },
  PR: { name: "Puerto Rico", cities: ["San Juan", "Bayamón", "Carolina", "Ponce", "Caguas", "Guaynabo", "Mayagüez", "Trujillo Alto", "Arecibo", "Fajardo", "Levittown", "Vega Baja", "Aguadilla", "Humacao", "Cayey", "Toa Baja", "Toa Alta", "Manatí", "Canóvanas", "Isabela", "Yauco", "Dorado", "Guayama", "Rincón", "Luquillo", "Río Grande", "Culebra", "Vieques", "Lajas", "Cabo Rojo", "San Germán", "Jayuya", "Utuado", "Adjuntas", "Orocovis", "Coamo", "Salinas", "Arroyo", "Patillas", "Naguabo"] }
};

export async function GET(request) {
  const { searchParams } = new URL(request.url);
  const query = searchParams.get("q")?.toLowerCase().trim();

  if (!query || query.length < 2) {
    return NextResponse.json({ cities: [] });
  }

  // Función para normalizar texto (quitar tildes/acentos)
  const normalizeText = (text) => {
    return text
      .toLowerCase()
      .normalize("NFD")
      .replace(/[\u0300-\u036f]/g, "");
  };

  const normalizedQuery = normalizeText(query);
  const results = [];

  // Buscar en todas las ciudades de todos los países
  for (const [countryCode, countryData] of Object.entries(citiesDatabase)) {
    for (const city of countryData.cities) {
      const normalizedCity = normalizeText(city);
      if (normalizedCity.includes(normalizedQuery)) {
        results.push({
          name: city,
          country: countryCode,
          countryName: countryData.name
        });
        
        // Limitar resultados para mejor rendimiento
        if (results.length >= 20) break;
      }
    }
    if (results.length >= 20) break;
  }

  // Ordenar: primero las que empiezan con el query, luego las que lo contienen
  results.sort((a, b) => {
    const aStarts = normalizeText(a.name).startsWith(normalizedQuery);
    const bStarts = normalizeText(b.name).startsWith(normalizedQuery);
    if (aStarts && !bStarts) return -1;
    if (!aStarts && bStarts) return 1;
    return a.name.localeCompare(b.name);
  });

  return NextResponse.json({ cities: results });
}
